# Generated by Django 5.1.2 on 2024-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.CharField(max_length=15)),
                ('registration_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
    ]
